export const books = [
  {
    bookId: "B001",
    title: "To Kill a Mockingbird",
    coverPage: "https://cdn.britannica.com/21/182021-050-666DB6B1/book-cover-To-Kill-a-Mockingbird-many-1961.jpg",
    author: "Harper Lee",
    genre: "Fiction",
    publicationDate: "1960-07-11",
    isbn: "978-0-06-112008-4",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A gripping story of racial injustice in the American South, seen through the eyes of young Scout Finch."
  },
  {
    bookId: "B002",
    title: "1984",
    coverPage: "https://m.media-amazon.com/images/I/81m-yfhwlfL._AC_UF1000,1000_QL80_.jpg",
    author: "George Orwell",
    genre: "Dystopian",
    publicationDate: "1949-06-08",
    isbn: "978-0-452-28423-4",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A chilling portrayal of a totalitarian society under constant surveillance and control."
  },
  {
    bookId: "B003",
    title: "Pride and Prejudice",
    coverPage: "https://ih1.redbubble.net/image.4211503559.0687/flat,750x,075,f-pad,750x1000,f8f8f8.jpg",
    author: "Jane Austen",
    genre: "Romance",
    publicationDate: "1813-01-28",
    isbn: "978-0-19-953556-9",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A classic romance that delves into issues of class, marriage, and personal growth in Georgian England."
  },
  {
    bookId: "B004",
    title: "The Alchemist",
    coverPage: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
    author: "Paulo Coelho",
    genre: "Adventure",
    publicationDate: "1988-05-01",
    isbn: "978-0-06-112241-5",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "An inspiring tale about following one's dreams and discovering life's true purpose."
  },
  {
    bookId: "B005",
    title: "Harry Potter and the Sorcerer's Stone",
    coverPage: "https://rukminim2.flixcart.com/image/850/1000/jskofww0/book/8/8/9/harry-potter-and-the-sorcerer-s-stone-book-1-original-imafe3mzc6vs5ta5.jpeg?q=90&crop=false",
    author: "J.K. Rowling",
    genre: "Fantasy",
    publicationDate: "1997-06-26",
    isbn: "978-0-590-35340-3",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "The magical journey begins for young wizard Harry Potter as he discovers his place at Hogwarts."
  },
  {
    bookId: "B006",
    title: "Moby-Dick",
    coverPage: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471137235/moby-dick-9781471137235_hr.jpg",
    author: "Herman Melville",
    genre: "Adventure",
    publicationDate: "1851-11-14",
    isbn: "978-0-14-243724-7",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "An epic sea adventure exploring the obsession of Captain Ahab with the great white whale, Moby Dick."
  },
  {
    bookId: "B007",
    title: "War and Peace",
    coverPage: "https://res.cloudinary.com/hzpwrwfdi/image/upload/w_220/media/covers/91FXycpulgL_txeuw9",
    author: "Leo Tolstoy",
    genre: "Historical",
    publicationDate: "1869-01-01",
    isbn: "978-0-19-923276-5",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "Tolstoy's masterpiece chronicles the lives of Russian aristocrats during the Napoleonic Wars."
  },
  {
    bookId: "B008",
    title: "The Odyssey",
    coverPage: "https://cdn.kobo.com/book-images/1c003baf-c48d-45be-9fd3-bc9c2bc6a685/1200/1200/False/the-odyssey-172.jpg",
    author: "Homer",
    genre: "Epic",
    publicationDate: "800-01-01",
    isbn: "978-0-14-026886-7",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "Homer’s timeless epic follows Odysseus’s long journey home after the Trojan War."
  },
  {
    bookId: "B009",
    title: "Crime and Punishment",
    coverPage: "https://m.media-amazon.com/images/I/A193gO2P8WL._AC_UF1000,1000_QL80_.jpg",
    author: "Fyodor Dostoevsky",
    genre: "Psychological Fiction",
    publicationDate: "1866-01-01",
    isbn: "978-0-14-044913-6",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A deep dive into the mind of a young man torn by morality and guilt after committing a crime."
  },
  {
    bookId: "B010",
    title: "The Brothers Karamazov",
    coverPage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDJLu8kTQbr6YZDYwU9MU780xTB_f2YFIcvg&s",
    author: "Fyodor Dostoevsky",
    genre: "Philosophical Fiction",
    publicationDate: "1880-01-01",
    isbn: "978-0-14-044924-2",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A philosophical exploration of faith, doubt, and family in Russia’s turbulent 19th century."
  },
  {
    bookId: "B011",
    title: "The Divine Comedy",
    coverPage: "https://m.media-amazon.com/images/I/51i-9SGWr-L._AC_UF1000,1000_QL80_.jpg",
    author: "Dante Alighieri",
    genre: "Epic Poetry",
    publicationDate: "1320-01-01",
    isbn: "978-0-14-044895-5",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A spiritual journey through Hell, Purgatory, and Heaven that explores sin and redemption."
  },
  {
    bookId: "B012",
    title: "The Book Thief",
    coverPage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6jKpHr56hxsjlyKQ6ozUQtQELVkIo86wBew&s",
    author: "Markus Zusak",
    genre: "Historical Fiction",
    publicationDate: "2005-03-14",
    isbn: "978-0-552-15041-4",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A poignant tale of a young girl's resilience and courage in Nazi Germany, narrated by Death."
  },
  {
    bookId: "B013",
    title: "Brave New World",
    coverPage: "https://m.media-amazon.com/images/I/618lb8MnrhL._AC_UF1000,1000_QL80_.jpg",
    author: "Aldous Huxley",
    genre: "Dystopian",
    publicationDate: "1932-08-31",
    isbn: "978-0-06-085052-4",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "Huxley's vision of a future society shaped by genetic engineering and rigid social control."
  },
  {
    bookId: "B014",
    title: "The Hobbit",
    coverPage: "https://rukminim2.flixcart.com/image/720/864/l2ghgnk0/book/r/3/w/the-hobbit-original-imagdsy4qspgcjgz.jpeg?q=60&crop=false",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    publicationDate: "1937-09-21",
    isbn: "978-0-618-00221-3",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "A delightful adventure with Bilbo Baggins, a hobbit who unexpectedly joins a quest."
  },
  {
    bookId: "B015",
    title: "One Hundred Years of Solitude",
    coverPage: "https://m.media-amazon.com/images/I/81oAEEwxBWL._AC_UF1000,1000_QL80_.jpg",
    author: "Gabriel García Márquez",
    genre: "Magical Realism",
    publicationDate: "1967-05-30",
    isbn: "978-0-06-088328-7",
    availability: true,
    location: "Aisle 3, Shelf B",
    bio: "An epic tale of the Buendía family and their fantastical lives in the town of Macondo."
  }
];


export const manga = [
  {
    bookId: "M001",
    title: "Naruto",
    coverPage: "",
    author: "Masashi Kishimoto",
    genre: "Action, Adventure",
    publicationDate: "1999-09-21",
    isbn: "978-1-56931-900-0",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M002",
    title: "One Piece",
    coverPage: "",
    author: "Eiichiro Oda",
    genre: "Adventure, Fantasy",
    publicationDate: "1997-07-22",
    isbn: "978-1-4215-0760-8",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M003",
    title: "Attack on Titan",
    coverPage: "",
    author: "Hajime Isayama",
    genre: "Action, Dark Fantasy",
    publicationDate: "2009-09-09",
    isbn: "978-1-61262-024-5",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M004",
    title: "Dragon Ball",
    coverPage: "",
    author: "Akira Toriyama",
    genre: "Adventure, Fantasy",
    publicationDate: "1984-12-03",
    isbn: "978-1-4215-0631-1",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M005",
    title: "Death Note",
    coverPage: "",
    author: "Tsugumi Ohba",
    genre: "Mystery, Thriller",
    publicationDate: "2003-12-01",
    isbn: "978-1-4215-0172-9",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M006",
    title: "Fullmetal Alchemist",
    coverPage: "",
    author: "Hiromu Arakawa",
    genre: "Adventure, Fantasy",
    publicationDate: "2001-07-12",
    isbn: "978-1-4215-0071-5",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M007",
    title: "My Hero Academia",
    coverPage: "",
    author: "Kohei Horikoshi",
    genre: "Action, Superhero",
    publicationDate: "2014-07-07",
    isbn: "978-1-4215-8040-2",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M008",
    title: "Tokyo Ghoul",
    coverPage: "",
    author: "Sui Ishida",
    genre: "Dark Fantasy, Horror",
    publicationDate: "2011-09-08",
    isbn: "978-1-4215-9185-9",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M009",
    title: "Demon Slayer: Kimetsu no Yaiba",
    coverPage: "",
    author: "Koyoharu Gotouge",
    genre: "Adventure, Dark Fantasy",
    publicationDate: "2016-02-15",
    isbn: "978-1-9747-0689-8",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M010",
    title: "Bleach",
    coverPage: "",
    author: "Tite Kubo",
    genre: "Adventure, Supernatural",
    publicationDate: "2001-08-07",
    isbn: "978-1-4215-0210-7",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M011",
    title: "Hunter x Hunter",
    coverPage: "",
    author: "Yoshihiro Togashi",
    genre: "Adventure, Fantasy",
    publicationDate: "1998-03-03",
    isbn: "978-1-4215-0210-7",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M012",
    title: "Fairy Tail",
    coverPage: "",
    author: "Hiro Mashima",
    genre: "Adventure, Fantasy",
    publicationDate: "2006-08-02",
    isbn: "978-1-4215-1320-2",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M013",
    title: "Sword Art Online",
    coverPage: "",
    author: "Reki Kawahara",
    genre: "Sci-Fi, Adventure",
    publicationDate: "2009-04-10",
    isbn: "978-0-316-38790-5",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M014",
    title: "Berserk",
    coverPage: "",
    author: "Kentaro Miura",
    genre: "Dark Fantasy, Horror",
    publicationDate: "1989-08-25",
    isbn: "978-1-59307-020-8",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
  {
    bookId: "M015",
    title: "Neon Genesis Evangelion",
    coverPage: "",
    author: "Yoshiyuki Sadamoto",
    genre: "Psychological, Sci-Fi",
    publicationDate: "1995-12-26",
    isbn: "978-1-56931-368-8",
    availability: true,
    location: "Aisle 3, Shelf B",
  },
];
